---
- hosts: all
  tasks:
  - name: Install multiple packages
    win_chocolatey:
      name: '{{ item }}'
      state: present
    with_items:
    - googlechrome
    - firefox
    - fslogix
    - fslogix-rule
    - notepadplusplus
    - citrix-workspace
    - winscp
    - putty
    - 7zip

