---
- hosts: all
  collections:
    - chocolatey.chocolatey.win_chocolatey
  tasks:
  - name: Install Admin Tools
    chocolatey.chocolatey.win_chocolatey:
        name: '{{ item }}'
        state: present
        pinned: yes
        architecture: x86
        force: yes
    with_items:
    - winscp
